# Generated by Django 3.2 on 2021-05-05 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='city',
        ),
        migrations.AddField(
            model_name='city',
            name='vendor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vendor'),
        ),
    ]
